# Generated by Django 4.2.27 on 2026-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_data", models.CharField(max_length=100)),
                ("final_score", models.IntegerField(default=-1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(default="Django API", max_length=100),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Health Records",
                "ordering": ["-timestamp"],
            },
        ),
    ]
