# Generated by Django 4.2.27 on 2026-01-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "description",
                    models.CharField(
                        default="Django API",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plans",
                    models.CharField(
                        choices=[
                            ("tier1", "tier1"),
                            ("tier2", "tier2"),
                            ("tier3", "tier3"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal_productivity", "personal_productivity"),
                            ("product_management", "product_management"),
                            ("b2b", "b2b"),
                            ("agent_wrappers", "agent_wrappers"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        default="Django API",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Detect",),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.user"
            ),
        ),
    ]
