# Generated by Django 4.2.27 on 2026-01-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_post_user_delete_detect_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(default="Django API", max_length=100),
        ),
    ]
